POST http://localhost:1337/post/create HTTP/1.1
content-type: application/json

{
    "title": "Title Number One",
    "text":"one plus one is two three four five six",
    "subtitle":"Lorem ipsum dolor  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia provident, similique cumque alias laboriosam fuga, voluptatibus quibusdam at laudantium ex reiciendis sit sapiente assumenda excepturi delectus quidem velit? Sed, vel.sit amet consectetur adipisicing elit. Quia provident, similique cumque alias laboriosam fuga, voluptatibus quibusdam at laudantium ex reiciendis sit sapiente assumenda excepturi delectus quidem velit? Sed, vel. ",
    "author":"Ktyawer awef"
}

### 
GET http://localhost:1337/post HTTP/1.1
content-type: application/json


### 
GET http://localhost:1337/post/61c4373ef34f6101056722b2 HTTP/1.1
content-type: application/json