POST http://localhost:1337/post/create HTTP/1.1
content-type: application/json

{
    "title": "About Something Intresting",
    "subtitle":"Fxs Lorem ipsum dolor   Lorem ipsum dolor sit",
    "text":"Lorem ipsum dolor   Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia provident, s Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia provident, s Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia provident, s Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia provident, s Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia provident, sLorem ipsum dolor sit amet consectetur adipisicing elit. Quia provident, similique cumque alias laboriosam fuga, voluptatibus quibusdam at laudantium ex reiciendis sit sapiente assumenda excepturi delectus quidem velit? Sed, vel.sit amet consectetur adipisicing elit. Quia provident, similique cumque alias laboriosam fuga, voluptatibus quibusdam at laudantium ex reiciendis sit sapiente assumenda excepturi delectus quidem velit? Sed, vel. ",
    "author":"Kyaw Myo Tun"
}

### 
GET http://localhost:1337/post HTTP/1.1
content-type: application/json


### 
GET http://localhost:1337/post/61c44f898d141e9dffe718c5 HTTP/1.1
content-type: application/json